name: Compile markdown and write into Woltlab Forum pages
description: ''
runs:
  using: docker
  image: Dockerfile
inputs:
  dbhost:
    description: 'Database host'
    required: true
    default: ''
  dbport:
    description: 'Database port'
    required: false
    default: '3306'
  dbuser:
    description: 'Database user'
    required: true
    default: ''
  dbpass:
    description: 'Database password'
    required: true
    default: ''
  dbname:
    description: 'Database name'
    required: true
    default: ''
  wbbtableid:
    description: 'WBB Table Id'
    required: true
    default: '1'
  stagingbranch:
    description: 'branch to use for staging'
    required: false
    default: 'dev'
  stagingpath:
    description: 'path to prepend for staging'
    required: false
    default: '/staging'
  dateformat:
    description: 'format on how to display date'
    required: false
    default: 'YYYY-MM-DD  HH:mm:ss'
